####
GET http://localhost:4004/test/Books

####
GET http://localhost:4004/test/Books(1)

####
GET http://localhost:4004/test/Books/1/getStock()
Authorization: Basic base64-user-password

####
GET http://localhost:4004/test/Books(1)/CatalogService.getStock()

####
POST http://localhost:4004/test/Books/1/buyBook
Content-Type: application/json
Authorization: Basic base64-user-password

{}