####
GET http://localhost:4004/test/Books

####
GET http://localhost:4004/test/Books(2)

#### Unbound function
GET http://localhost:4004/test/calculateTotalStock()

#### Unbound Action
POST http://localhost:4004/test/resetAllBooks
Content-Type: application/json
Authorization: Basic base64-user-password

{}

#### Bound Function
GET http://localhost:4004/test/Books(2)/getStock()

#### Bound Action
POST http://localhost:4004/test/Books(5)/buyBook
Content-Type: application/json
Authorization: Basic base64-user-password

{
}